name: de_comp
description: "A component architecture for scalable applications"
version: 0.0.5
homepage: https://github.com/karroze/de_comp
repository: https://github.com/karroze/de_comp

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  de_comp_core: ^0.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0

dev_dependencies:
  very_good_analysis: ^7.0.0

