name: de_comp
description: "A component architecture for scalable applications"
version: 0.0.1
homepage: https://github.com/karroze/de_comp

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  de_comp_core: ^0.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

